Odafuta-LPの機能追加
ogatakatsuya/Semi-A pull request #9
Opened 2024-06-18 10:45 UTC by odafuta

投票結果の表示機能とコメント投稿・表示機能をLPに追加しました。

2024-06-18 10:55 UTC, ogatakatsuya commented
LPどんな感じになってるか見たいので，コメントに画像貼ってもらってもいいですか？？😃
https://qiita.com/yando/items/d99fad2b2eb606c53f62

2024-06-18 11:31 UTC, ogatakatsuya requested changes
概ねいい感じです．変数埋め込んでいるところの再検討と画像を見せてもらいたいです！

2024-06-18 11:31 UTC, ogatakatsuya commented on src/routes/+page.svelte
> +
ここら辺routes/page.svelte編集しちゃってますが，コンフリクト起こらないように話し合ってくれてるんですかね

2024-06-18 11:31 UTC, ogatakatsuya commented on src/routes/CommentFeature.svelte
> +</section>
何かに対してリアクティブにしたい要素以外は変数で持つ必要はないので，静的なコンテンツはHTMLタグの中に埋め込んでしまって大丈夫です．例えばクライアント側の操作に応じてメッセージを変えるのであればこれでもおっけいです．（結構面白そう）

2024-06-18 11:31 UTC, ogatakatsuya commented on src/routes/ResultFeature.svelte
> +</section>
これに関しても同じく，そのまま埋め込んじゃって大丈夫です．あとtailwindcssっていう便利なフレームワークがあるので，素のcss当てるのもいいですが，使用を検討してみてください．

2024-06-19 02:42 UTC, odafuta commented on src/routes/CommentFeature.svelte
> +</section>
後々リアクティブ性付与したい時にできるように変数宣言しておきました。もし、今後変更ない感じでしたらHTMLの中で埋め込む感じで再編集しておきます。

2024-06-19 02:46 UTC, odafuta commented on src/routes/+page.svelte
> +
話し合ってなかったから今連絡だけいれました。ありがとうございます。

2024-06-19 02:47 UTC, odafuta commented
<img width="959" alt="LPfunction1_1" src="https://github.com/ogatakatsuya/Semi-A/assets/148888595/929b5821-fdeb-496e-a3cb-9886d2eb8004">
<img width="959" alt="LPfuntion1_2" src="https://github.com/ogatakatsuya/Semi-A/assets/148888595/32dcb159-d2e7-4e04-981a-a3be12eeb7d4">

画像こちらになります。よろしくお願いします。

2024-06-19 02:48 UTC, i-takechi commented
@odafuta 
内容作成ありがとう！コンフリクト諸々対応しておきます

2024-06-19 02:51 UTC, ogatakatsuya approved these changes
了解です！！デザイン等はこれからもっと考えていこう！
マージしてもらって大丈夫です

2024-06-19 02:52 UTC, odafuta commented
分かりました！ありがとう！

2024-06-19 02:52 UTC, merged